Cumulative Sales =
VAR _LastSalesDate = LASTDATE ( Sales[OrderDate] )
VAR _Result =
    CALCULATE (
        [Ventas netas (m2)],
        FILTER ( ALLSELECTED ( d_fechas ), d_fechas[Date] <= _last_sales_date )
    )
RETURN
    _result
