DEFINE
    VAR __DS0Core =
        FILTER (
            SUMMARIZECOLUMNS (
                'Dim_BU'[BU],
                'Dim_Heading'[Heading],
                'Dim_Heading'[Order],
                'Master_Data_AOCD1'[Capital generation],
                'Dim_Date'[Year],
                'Dim_Date'[Quarter],
                'Dim_Date'[YearQQ],
                'Dim_Date'[Month],
                'Dim_Date'[YearMth],
                "Total_Act", 'Measures Table'[Total Act],
                "Total_Plan", 'Measures Table'[Total Plan]
            ),
            (@QuarterParameter = "" || 'Dim_Date'[Quarter] = @QuarterParameter) &&
            (@YearParameter = "" || 'Dim_Date'[Year] = @YearParameter)
        )
    VAR __DS0BodyLimited =
        TOPN (
            500000,
            __DS0Core,
            'Dim_BU'[BU], 1,
            'Dim_Heading'[Order], 1,
            'Dim_Heading'[Heading], 1,
            'Master_Data_AOCD1'[Capital generation], 1,
            'Dim_Date'[Year], 1,
            'Dim_Date'[Quarter], 1,
            'Dim_Date'[YearQQ], 1,
            'Dim_Date'[Month], 1,
            'Dim_Date'[YearMth], 1
        )

EVALUATE
__DS0BodyLimited
ORDER BY
    'Dim_BU'[BU],
    'Dim_Heading'[Order],
    'Dim_Heading'[Heading],
    'Master_Data_AOCD1'[Capital generation],
    'Dim_Date'[Year],
    'Dim_Date'[Quarter],
    'Dim_Date'[YearQQ],
    'Dim_Date'[Month],
    'Dim_Date'[YearMth]


Private Sub Worksheet_Change(ByVal Target As Range)
    ' Declare the ranges for the two parameter cells
    Dim QuarterCell As Range
    Dim YearCell As Range

    ' Set the ranges for the quarter and year parameters
    Set QuarterCell = Range("SelectedQuarter") ' Cell for the quarter parameter
    Set YearCell = Range("SelectedYear") ' Cell for the year parameter

    ' Check if the changed cell is either the quarter or year parameter cell
    If Not Application.Intersect(QuarterCell, Target) Is Nothing Or _
       Not Application.Intersect(YearCell, Target) Is Nothing Then

        ' Call the macro to update the query with both parameters
        Call UpdateDAXQuery

    End If
End Sub
